name: splash_module_flutter
description: Modui.
version: 0.8.0
homepage:

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.3.2
  flutter_svg: ^2.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.3

flutter:
