name: splash_example
description: 'Um exemplo da splash_module sendo usada.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.3.2
  flutter_svg: ^2.0.8

  cupertino_icons: ^1.0.2

  splash_module_flutter:
    path: ../../splash_module_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - './assets'